const introductions = {
    "male_child": [ "A little boy walks into the animal shelter." ],
    "male_older": [ "An older gentleman walks into the animal shelter." ],
    "male_family": [ "A man walks into the animal shelter with two tiny humans." ],
    "female_child": [ "A little girl walks into the animal shelter." ],
    "female_older": [ "An older lady walks into the animal shelter." ],
    "female_family": [ "A woman walks into the animal shelter with two tiny humans." ],
    "neither_child": [ "A young child walks into the animal shelter." ],
    "neither_older": [ "An older person walks into the animal shelter." ],
    "neither_family": [ "Someone walks into the animal shelter with two tiny humans." ],
};

const describers = {
    "male": {
        "child": [],
        "older": [],
        "family": [],
        "nice": [],
        "rude": [],
        "hipster": [],
        "dog-lover": [],
        "cat-lover": [],
        "boomer": [],
        "lonely": [],
        "easily-impressed": [],
        "rich": [],
        "poor": [],
        "mid-income": [],
        "busy": [],
        "leisure": [],
        "sporadic": [],
        "fluffy": [],
        "smooth": [],
        "outdoorsy": [],
        "indoorsy": [],
        "exercise": [],
        "couchpotato": [],
        "vampire": [],
    },
    "female": {
        "child": [],
        "older": [],
        "family": [],
        "nice": [],
        "rude": [],
        "hipster": [],
        "dog-lover": [],
        "cat-lover": [],
        "boomer": [],
        "lonely": [],
        "easily-impressed": [],
        "rich": [],
        "poor": [],
        "mid-income": [],
        "busy": [],
        "leisure": [],
        "sporadic": [],
        "fluffy": [],
        "smooth": [],
        "outdoorsy": [],
        "indoorsy": [],
        "exercise": [],
        "couchpotato": [],
        "vampire": [],
    },
    "neither": {
        "child": [],
        "older": [],
        "family": [],
        "nice": [],
        "rude": [],
        "hipster": [],
        "dog-lover": [],
        "cat-lover": [],
        "boomer": [],
        "lonely": [],
        "easily-impressed": [],
        "rich": [],
        "poor": [],
        "mid-income": [],
        "busy": [],
        "leisure": [],
        "sporadic": [],
        "fluffy": [],
        "smooth": [],
        "outdoorsy": [],
        "indoorsy": [],
        "exercise": [],
        "couchpotato": [],
        "vampire": [],
    },
};

// --responses--
// denied:
// disappointed:
// interested:
// very interested:
// adopted:
